[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# PWA-specific headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Service worker headers
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "application/javascript"

# Manifest headers
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=3600"

# Icon headers
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Static assets caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML files (no caching for PWA updates)
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[build.environment]
  NODE_VERSION = "18"
  # API Configuration - Change these values for your backend
  VITE_API_URL = "http://127.0.0.1:8000/api"
  VITE_APP_TITLE = "MIPT - Industrial Training Reports"
  VITE_APP_DESCRIPTION = "Industrial Practical Training Report System"
  VITE_APP_VERSION = "1.0.0"
  VITE_PWA_ENABLED = "true"

# Environment-specific configurations
[context.production.environment]
  VITE_API_URL = "https://mipt.pythonanywhere.com/api"
  VITE_APP_TITLE = "MIPT - Industrial Training Reports"

[context.deploy-preview.environment]
  VITE_API_URL = "/api"
  VITE_APP_TITLE = "MIPT - Industrial Training Reports (Preview)"

[context.branch-deploy.environment]
  VITE_API_URL = "/api"
  VITE_APP_TITLE = "MIPT - Industrial Training Reports (Branch)" 